### PR TITLE
Cleanup db_access module

### PR DESCRIPTION
**Pull request by vxgmichel**
This PR removes the beacon plugin from the `db_access` module.

Instead, `db_access` can be injected with custom plugins using `db_access.__path__`. 

Here's an example: 
```python
from tango.databaseds import db_access
from tango.databaseds.database import main as base_main

# Assuming mypackage.db_access.myplugin exists
from mypackage import db_access as local_db_access


def main(args=None):
    # Give priority to the bliss db_access module
    db_access.__path__ = local_db_access.__path__ + db_access.__path__
    # Safety check
    from tango.databaseds.db_access import myplugin
    assert myplugin.__file__.startswith(local_db_access.__path__[0])
    # Run
    base_main(args)


if __name__ == "__main__":
    main()
```

### CODE REVIEW

**Review by ajoubertza — COMMENTED** [review]
Not sure of all the details around this, but changes look reasonable.  Is there an issue this relates to that has more of an explanation?
Just check the Python 3.7 tests that are failing.

**Comment by vxgmichel** [comment]
Hi @ajoubertza,

> Not sure of all the details around this, but changes look reasonable. Is there an issue this relates to that has more of an explanation?

Well I don't really know how we should deal with the databaseds module. On one hand it's not properly maintained, and it's not integrated in our CI so it could easily be moved to a separate project. On the other hand, having a robust and tested version of this module could help greatly with the test context and the rest of the test suite (since we wouldn't depend on the cpp databaseds `-file` option anymore).

Do you have an opinion?

> Just check the Python 3.7 tests that are failing.

Some of the tests seem to fail sporadically. I think we should create an issue about this and report every occurrence so we have a better idea of what's going on.

**Comment by ajoubertza** [comment]
Keeping databaseds in this repo sounds better than moving it out.  Sure, it would be nice if it had better testing and maintenance.  I guess that will only happen when someone really needs it.

**Review by ajoubertza — APPROVED** [review]
Tests are passing now, so OK with this one.

**Pull request merged**
