### PR TITLE
Better exception handling in server.run and test context (issue #131)

### PR DESCRIPTION
**Pull request by vxgmichel**
Fix issue #131.

### CODE REVIEW

**Comment by AntoineDupre** [comment]
### DeviceTestContext
What about exceptions after init_device, while the device is running or stopping ? 
Does it make sense to check the queue and raise exception in the stop() function ?

**Comment by vxgmichel** [comment]
@AntoineDupre 
> What about exceptions after init_device, while the device is running or stopping ?
Does it make sense to check the queue and raise exception in the stop() function ?

Does that actually happen?

**Comment by AntoineDupre** [comment]
It probably doesn't happens actually, but if it does at some point, the traceback will not be printed.

**Comment by vxgmichel** [comment]
Ok then! Also, what about the `omni_thread_fatal`error?

**Comment by AntoineDupre** [comment]
Hum ... I used ```raise``` instead of ```six.reraise``` in my prototype

**Comment by vxgmichel** [comment]
@AntoineDupre So, would you say it's ready to merge?

**Comment by LJBD** [comment]
+2 issues on Codacy, so I don't think so :)

**Review by AntoineDupre — APPROVED** [review]

**Pull request merged**
