### PR TITLE
Fix #192: Gevent server memory leak

### LINKED ISSUE #192: Gevent server on 9.2.3 memory leak
In PyTango 9.2.3 there is a memory leak in server in gevent mode.
The memory leak happens with every read request or command execution.

It seems to have origin in this commit: c90a409e6d5e3c61eca48f163e719a37db4c99e9

### PR DESCRIPTION
**Pull request by tiagocoutinho**
Issue #192.

This commit basically reverts c90a409.
To be honest I don't fully understand the cause  for the memory leak.

### CODE REVIEW

**Review by vxgmichel — COMMENTED** [review]
Hi Tiago, could you try `watcher.start(self.tasks.put_nowait, task)` instead?

**Comment by vxgmichel** [comment]
Hi @tiagocoutinho, did the leak reappear with the last change or is it ok?

**Comment by tiagocoutinho** [comment]
It looks ok with the last change (2afbbc5). Thanks for the suggestion.

**Comment by vxgmichel** [comment]
I'm a bit confused then, I was kind of expecting the leak to reappear... Something related to `watcher.stop` or `watcher.close` not being called, but now I have no idea about what is causing the leak.

**Comment by vxgmichel** [comment]
@tiagocoutinho I found the leak, it related to the watcher not being collected if `watcher.stop()` is not called.

**Pull request merged**
