### PR TITLE
Add EnsureOmniThread and is_omni_thread

### PR DESCRIPTION
**Pull request by ajoubertza**
Subscription to events from non-omniORB threads can result in application crashes.  A class has been added that exposes omniORB's `omni_thread::ensure_self`.  This should be used as a context handler
in user threads to fix this problem, like:

```python
class JobThread(threading.Thread):
    def run(self):
        with tango.EnsureOmniThread():
            pass  # do things with subscriptions...
```

Also added `is_omni_thread` which reports if a thread has an omniORB thread ID or not.  This could be used in future to warn or even raise an exception if methods that shouldn't be are called from non-omniORB threads.  E.g., `DeviceProxy.subscribe_event`.

Using `EnsureOmniThread` fixes issues #307.

(Partially helps with #292 - the reported example runs to completion, however, the underlying issue is not related to omni threads - so that isn't fixed by this PR).

(Does not help with issue #315 - subscription is happening from omni threads already)

### CODE REVIEW

**Comment by ajoubertza** [comment]
I see the Windows compilation on AppVeyor is failing with errors like:
```
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/posix.h(39): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\projects\pytango\_tango.vcxproj]
```
@NexeyaSGara could you please help with that?  I tried adding pthread-win32 to the appveyor file, but it hasn't fixed the problem.

**Comment by NexeyaSGara** [comment]
@ajoubertza can you try to add

include_directories(${PROJECT_NAME} PUBLIC "$ENV{PTHREAD_WIN}/include")

to the CMakeLists.txt ?

**Comment by ajoubertza** [comment]
@NexeyaSGara Thanks, I tried that.  I pushed that [change](https://github.com/ajoubertza/pytango/commit/1e98b15023b26f7fc7c3d615b854ad8e01223f39) to my own [fork](https://github.com/ajoubertza/pytango/tree/issue-307-context-handler) of the pytango repo, and also [disabled](https://github.com/ajoubertza/pytango/commit/a1f9736fcf44120538e7a291f1005bc56a6645f6) all but 1 of the AppVeyor platforms to speed things up.    

It gets a bit further but fails for a different reason:  https://ci.appveyor.com/project/ajoubertza/pytango/builds/30377141
```
C:\projects\pthreads-win32\include\pthread.h(320): error C2011: 'timespec': 'struct' type redefinition [C:\projects\pytango\_tango.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39): note: see declaration of 'timespec'
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(90): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\projects\pytango\_tango.vcxproj]
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(90): error C3646: 'count': unknown override specifier [C:\projects\pytango\_tango.vcxproj]
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(70): error C2614: 'omni_refcount': illegal member initialization: 'count' is not a base or member [C:\projects\pytango\_tango.vcxproj]
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(75): error C2065: 'count': undeclared identifier [C:\projects\pytango\_tango.vcxproj]
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(75): error C3861: 'InterlockedIncrement': identifier not found [C:\projects\pytango\_tango.vcxproj]
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(80): error C2065: 'count': undeclared identifier [C:\projects\pytango\_tango.vcxproj]
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(80): error C3861: 'InterlockedDecrement': identifier not found [C:\projects\pytango\_tango.vcxproj]
C:\projects\libtango\libtango_9.3.3_v140_x64\include\omnithread/atomic.h(86): error C2065: 'count': undeclared identifier [C:\projects\pytango\_tango.vcxproj]
```


Please can you continue debugging this issue in you own fork?

**Comment by NexeyaSGara** [comment]
@ajoubertza 
I looked at 
https://github.com/tango-controls/cppTango/blob/tango-9-lts/configure/cmake_win_defs.cmake

We have put : 

`if(MSVC14)
    add_definitions(-D_TIMERS_T_)
    add_definitions(-DHAVE_STRUCT_TIMESPEC)
    add_definitions(-D_TIMESPEC_DEFINED)
    add_definitions(-DSTRUCT_TIMESPEC_HAS_TV_SEC)
    add_definitions(-DSTRUCT_TIMESPEC_HAS_TV_NSEC)
endif(MSVC14)`

Seems that the version you tested is the only one that need this fix

**Comment by ajoubertza** [comment]
@NexeyaSGara Thanks for fixing the AppVeyor compilation!

**Pull request merged**
