### PR TITLE
Modify macro definition for Tango version > 9.2.5

### PR DESCRIPTION
**Pull request by grm84**
Issue #196

### CODE REVIEW

**Comment by vxgmichel** [comment]
`DevVarBooleanArray` is still causing problems apparently:

```
/home/travis/build/tango-controls/pytango/ext/device_data.cpp: In instantiation of ‘boost::python::api::object PyDeviceData::extract_array(Tango::DeviceData&, boost::python::api::object&, PyTango::ExtractAs) [with long int tangoArrayTypeConst = 21l]’:
/home/travis/build/tango-controls/pytango/ext/device_data.cpp:196:9:   required from here
/home/travis/build/tango-controls/pytango/ext/device_data.cpp:162:18: error: no match for ‘operator>>’ (operand types are ‘Tango::DeviceData’ and ‘const TangoArrayType* {aka const Tango::DevVarBooleanArray*}’)
             self >> tmp_ptr;
                  ^
```

**Comment by grm84** [comment]
Looks like the #define code is OK.

What version of Tango is this compiled against?



________________________________

**Comment by vxgmichel** [comment]
> What version of Tango is this compiled against?

It fails for both 9.2.2 and 9.2.5a.

**Comment by vxgmichel** [comment]
Thanks @grm84 !

**Pull request merged**
