### PR TITLE
Move tango object server to its own module

### PR DESCRIPTION
**Pull request by vxgmichel**
@tiagocoutinho This PR is pretty harmless, it's only about moving some code and cleaning up. The only backward compatibility issue I can think of is that every `Server` import:
```python
from tango.server import Server 
```
should be replaced with:
```python
from tango.tango_object import Server
```
Is that a problem?

### CODE REVIEW

**Comment by tiagocoutinho** [comment]
I would say 565d939 it is quite harmful. Everyone in the community is doing in their servers: `from tango.server import Server`. This will break their code, won't it?
I don't understand what is the rationale for moving the Server from server module to tango_object?

**Comment by vxgmichel** [comment]
@tiagocoutinho I'm sorry if I missed the use case for server.Server, but I thought it was directly related to tango objects. Are you saying it is used in other contexts?

**Comment by tiagocoutinho** [comment]
I made a small mistake:
Most servers are usually using `tango.server.run` and not `tango.server.Server`.
Still, I would consider  `tango.server.Server` as part of the API.
Here is an example were I use it [LimaDS prototype](https://gitlab.esrf.fr/snippets/2).

I would ok with moving `Server` to `tango.tango_object` but only if we expose it in `tango.server` as well (at least for the moment).

What do you think?

**Comment by vxgmichel** [comment]
> I would be ok with moving Server to tango.tango_object but only if we expose it in tango.server as well (at least for the moment).

The only issue is related to circular imports (`tango.tango_object` imports `tango.server`). How would you deal with that?

**Comment by vxgmichel** [comment]
Also, let me know if you want a better name for the `tango.tango_object` module (`tango.object` maybe?)

**Comment by vxgmichel** [comment]
@tiagocoutinho is the solution from 396290c OK with you?

**Comment by tiagocoutinho** [comment]
Great. I accept it

**Pull request merged**
