### PR TITLE
Investigate event test failures on Travis CI

### PR DESCRIPTION
**Pull request by ajoubertza**
This branch is for investigating the travis-only failures with the event subscription tests (e.g. travis builds [386](https://travis-ci.org/tango-controls/pytango/builds/466891548) and [387](https://travis-ci.org/tango-controls/pytango/builds/467906826)).

No need to review yet!

### CODE REVIEW

**Comment by ajoubertza** [comment]
@tiagocoutinho, continuing the discussions from PR #245, I've done some more investigating.  I created an Ubuntu 16.04 VM, using VirtualBox and Vagrant.  I did the basic installation steps that are done before a travis build (mostly installing TANGO via conda, using Python 2.7).  I get the same kind of event test failures when running the unit tests locally.

Next I made a script that duplicates the `EventDevice` from `test_events.py`  as a standalone DS, and then created a client that does the same thing that the unit tests do.   I run the `EventDevice` via the test context:
```
python -m tango.test_context EventDS.EventDevice --host 10.0.2.15 &
```
And launch the client using the connection string reported by the DS:
```
python event_client.py tango://10.0.2.15:8888/test/nodb/eventdevice#dbase=no
```

After the initial subscription we get the first "event" with `value = 0.0`, which you said doesn't come via ZMQ:
```
EventData[
     attr_name = 'tango://10.0.2.15:8888/test/nodb/eventdevice/attr#dbase=no'
    attr_value = DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'attr', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1546457423, tv_usec = 803792), type = tango._tango.CmdArgType.DevDouble, value = 0.0, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None)
        device = EventDevice(test/nodb/eventdevice)
           err = False
        errors = ()
         event = 'change'
reception_date = TimeVal(tv_nsec = 0, tv_sec = 1546457423, tv_usec = 803857)]
```

After that, there are no events for about 10 seconds, and then I start seeing events.  Interestingly, I get 2 events in a row each time.  The first is an error message about the event channel, and the second looks like a valid event, but the `value` is still `0.0`, so not the `1.0` that we expect for the real event.
```
bad event:
EventData[
     attr_name = 'tango://10.0.2.15:8888/test/nodb/eventdevice/attr#dbase=no'
    attr_value = None
        device = EventDevice(test/nodb/eventdevice)
           err = True
        errors = (DevError(desc = 'Event channel is not responding anymore, maybe the server or event system is down', origin = 'EventConsumer::KeepAliveThread()', reason = 'API_EventTimeout', severity = tango._tango.ErrSeverity.ERR),)
         event = 'change'
reception_date = TimeVal(tv_nsec = 0, tv_sec = 1546457435, tv_usec = 782275)]

good event:
EventData[
     attr_name = 'tango://10.0.2.15:8888/test/nodb/eventdevice/attr#dbase=no'
    attr_value = DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'attr', nb_read = 1, nb_written = 0, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1546457435, tv_usec = 783979), type = tango._tango.CmdArgType.DevDouble, value = 0.0, w_dim_x = 0, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 0, dim_y = 0), w_value = None)
        device = EventDevice(test/nodb/eventdevice)
           err = False
        errors = ()
         event = 'idl5_change'
reception_date = TimeVal(tv_nsec = 0, tv_sec = 1546457435, tv_usec = 784022)]
```

Then I also created a script that subscribes to all ZMQ topics and prints out the messages it gets.  If I connect it to (what I think is) the ZMQ port, I can see a message coming through every time I execute the `send_event` command via a DeviceProxy.  I get messages like these:
```
./topics_sub.py tcp://10.0.2.15:42747
Receiving messages on ALL topics...

   Rx msg:['tango://vagrant:8888/test/nodb/eventdevice/attr#dbase=no.idl5_change', '\x01', '\x01\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\xc0\xde\xc0\xde\x05\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00,\x19-\\\x18d\t\x00\x00\x00\x00\x00\x05\x00\x00\x00attr\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
   Rx msg:['I like beer']
   Rx msg:['tango://vagrant:8888/test/nodb/eventdevice/attr#dbase=no.idl5_change', '\x01', '\x01\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '\xc0\xde\xc0\xde\x05\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x000\x19-\\\xb1\xac\x01\x00\x00\x00\x00\x00\x05\x00\x00\x00attr\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
```

The messages are using the hostname (`vagrant`), instead of the IP address, even though the DS was launched using an IP address.  I assume this mismatch is what breaks the event system.

If I launch the DS using the hostname, then the client does get the events as expected.
Similarly, if I force the hostname in the unit tests, then they pass.

Unfortunately, the travis tests using the hostname lookup still [fail](https://travis-ci.org/tango-controls/pytango/jobs/471396987), even though the lookup seems to work.

Any ideas?

**Comment by tiagocoutinho** [comment]
I have seen this double event before. It happens every 10s right? This is the Tango event system heartbeat at work. It tries to connect to events and fails (first event) but then it reads the attribute and it works so it propagates it as if there was a connection.

Similar thing happened before: In the past it was due to a discrepancy in an internal C++ field. At the time I remember on one side the event name was being calculated having the tango host as the user wrote it and on the other side either it had the fully qualified hostname or the IP (can't remember exactly). I suspect that this is back again to haunt us in another very similar way.

**Comment by tiagocoutinho** [comment]
Do you know how many network interfaces are visible in the travis docker image?

If there are more than one, then maybe tango resolves the network address differently / randomly?

**Comment by ajoubertza** [comment]
@tiagocoutinho I've been discussing this issue with @bourtemb.  He also mentioned the double update every 10 seconds from the heartbeat.  And that cppTango 9.3 has fixes for the event issues - now the server is the only one deciding on the channel name, and it gets sent to the client, so things should be more consistent.  He also said that using events with the "dbase=no" option is not supported, so we're lucky if it works.  His suggestion was to use a real TANGO DB for the tests.

What is interesting is that the tests are failing if we start the test context device with the hostname, but passing if we use the IP.  And in the case that IP is used, the ZMQ end points and channel names are actually using the hostname!  E.g.,
```
1549491039 [139701072799488] DEBUG dserver/EventDevice/EventDevice Sending event_topic = tango://travis-job-ea62f0d2-2491-453b-bbb6-846e1eca59ff:52673/test/nodb/eventdevice/attr#dbase=no.idl5_change
1549491039 [139701072799488] DEBUG dserver/EventDevice/EventDevice DeviceImpl::adm_name arrived
1549491039 [139701072799488] DEBUG dserver/EventDevice/EventDevice Leaving DeviceImpl::adm_name
1549491039 [139701072799488] DEBUG dserver/EventDevice/EventDevice Sending channel_name = tango://travis-job-ea62f0d2-2491-453b-bbb6-846e1eca59ff:52673/dserver/eventdevice/eventdevice
``` 
(this is from build 406.1 - https://api.travis-ci.org/v3/job/489774029/log.txt)

> Do you know how many network interfaces are visible in the travis docker image?

A while ago, Travis was reporting the IP addresses and it showed 2.  No the logs don't show any IP information, so I don't know.

**Comment by ajoubertza** [comment]
After updating cppTango to v9.3.2, tests work, so closing this.  It will be included in PR #250.

**Pull request closed without merging**
