### PR TITLE
Make sure we only convert to string python unicode/str/bytes objects

### LINKED ISSUE #285: Server on Py3 seg faults on wrong command/attribute result
On python 3, a pytango server segfaults in the following scenarios.

* command is supposed to return a string/string[] and returns something else
* attribute is supposed to return a string/string[]/string[][] and returns something else

On python 2, a TypeError is raised

Tested with PyTango 9.3.1dev1 on linux mint 19 64bits with Tango c++ 9.3.3

The following examples all fail:
```python
from tango.server import Device, attribute, command
BAD_STR = 1.2345
BAD_LIST = ['bad', 1.2345]

class DevTest(Device):

    @attribute(dtype=str)
    def a1(self):
        return BAD_STR

    @attribute(dtype=[str])
    def a1(self):
        return BAD_LIST

    @command(dtype_out=('str',))
    def DbGetProperty(self, argin):
        return BAD_LIST

DevTest.run_server()
```

### PR DESCRIPTION
**Pull request by tiagocoutinho**
Fixes #285 

Only convert to C string python str/bytes/unicode objects.
On error raise TypeError

### CODE REVIEW

**Review by ajoubertza — CHANGES_REQUESTED** [review]
Please add unit tests that check the examples you provided in the issue.  That will provide more confidence that this fix works.  

(As with PR #289, Py 2.7 tests failing because of pytest version)

**Comment by tiagocoutinho** [comment]
> Please add unit tests that check the examples you provided in the issue. That will provide more confidence that this fix works.

Sure, I am on it :-)

**Comment by tiagocoutinho** [comment]
Ok, it should be better now

**Review by ajoubertza — APPROVED** [review]
LGTM

**Pull request merged**
