### PR TITLE
Codacy badge in README and code quality policy in How to Contribute

### PR DESCRIPTION
**Pull request by LJBD**
I've added a Codacy badge to README and properly placed it.
I've also updated How to Contribute section so that it includes the policy we've agreed upon.
Related issue: #133

### CODE REVIEW

**Comment by LJBD** [comment]
All right, I'll solve the conflicts.

**Comment by LJBD** [comment]
Do you think it's all right to have that policy listed as a warning in the docs?

**Comment by vxgmichel** [comment]
Looks good!

> Do you think it's all right to have that policy listed as a warning in the docs?

Yea maybe it's a bit too scary, we don't want to prevent people from contributing.

**Comment by LJBD** [comment]
Okay, I'll change it to a note.

**Comment by vxgmichel** [comment]
Thanks!

**Pull request merged**
