### PR TITLE
Change for collections abstract base class

### PR DESCRIPTION
**Pull request by grm84**
The `collections.abc` was introduced at python 3.3. This is a proactive change as the original collections code will be deprecated at python3.8.
`inspect.getargspec` is already deprecated.

### CODE REVIEW

**Comment by vxgmichel** [comment]
LGTM, thanks @grm84 !

**Review by ajoubertza — CHANGES_REQUESTED** [review]
Thanks for updates @grm84.  Please add some details to the PR description about why this change is proposed.  Is there a related issue?  I would have thought we'd have hit Python 3.3 issues long ago.

We need the CI tests to pass, but I guess you're still working on that.

**Comment by grm84** [comment]
Hi @ajoubertza The collections.abc was introduced at python 3.3. This is a proactive change as the original collections code will be deprecated at python3.8. inspect.getargspec is deprecated

**Comment by vxgmichel** [comment]
@ajoubertza 
> We need the CI tests to pass, but I guess you're still working on that.

It seems that all the tests that require a connection to the "dserver" device are failing (dserver/testdevice/testdevice). I have no idea what could cause this, but I don't think it is related to the PR. I'll run a quick investigation.

**Comment by ajoubertza** [comment]
Thanks for looking at the tests @vxgmichel.

**Comment by vxgmichel** [comment]
I ran the tests in a fresh environment, similar to the one created in travis and the tests pass:

```
$ python setup.py test --addopts '-k "test_event or test_polled"'
================================================ test session starts =================================================
platform linux -- Python 3.7.1, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vimiche/miniconda/envs/buildenv/bin/python
cachedir: .pytest_cache
rootdir: /home/vimiche/pytango, inifile: setup.cfg
plugins: forked-0.2, xdist-1.24.1
collected 655 items / 637 deselected                                                                                 

tests/test_event.py::test_subscribe_change_event[Synchronous] PASSED                                           [  5%]
tests/test_event.py::test_subscribe_interface_event[Synchronous] PASSED                                        [ 11%]
tests/test_event.py::test_push_event_with_timestamp[Synchronous] PASSED                                        [ 16%]
tests/test_event.py::test_subscribe_change_event[Futures] PASSED                                               [ 22%]
tests/test_event.py::test_subscribe_interface_event[Futures] PASSED                                            [ 27%]
tests/test_event.py::test_push_event_with_timestamp[Futures] PASSED                                            [ 33%]
tests/test_event.py::test_subscribe_change_event[Asyncio] PASSED                                               [ 38%]
tests/test_event.py::test_subscribe_interface_event[Asyncio] PASSED                                            [ 44%]
tests/test_event.py::test_push_event_with_timestamp[Asyncio] PASSED                                            [ 50%]
tests/test_event.py::test_subscribe_change_event[Gevent] PASSED                                                [ 55%]
tests/test_event.py::test_subscribe_interface_event[Gevent] PASSED                                             [ 61%]
tests/test_event.py::test_push_event_with_timestamp[Gevent] PASSED                                             [ 66%]
tests/test_server.py::test_polled_command[Synchronous] PASSED                                                  [ 72%]
tests/test_server.py::test_polled_command[Asyncio] PASSED                                                      [ 77%]
tests/test_server.py::test_polled_command[Gevent] PASSED                                                       [ 83%]
tests/test_server.py::test_polled_attribute[Synchronous] PASSED                                                [ 88%]
tests/test_server.py::test_polled_attribute[Asyncio] PASSED                                                    [ 94%]
tests/test_server.py::test_polled_attribute[Gevent] PASSED                                                     [100%]

===================================== 18 passed, 637 deselected in 3.93 seconds ======================================
```

**Comment by ajoubertza** [comment]
Weird that those tests pass for you @vxgmichel.  Any ideas about the CI?  We need it to work.

@grm84 There are few places where further changes are required - probably won't fix CI, but please change these:
- `server.py:241` is still using `inspect.getargspec` instead of `inspect_getargspec`
- `tango_object.py:133` needs the same (and the new import)

**Comment by grm84** [comment]
Hi @ajoubertza, Well spotted, I completely missed those. Lets see if the tests pass now!

**Comment by vxgmichel** [comment]
I ran [the travis docker image locally](https://docs.travis-ci.com/user/common-build-problems/#running-a-container-based-docker-image-locally) and the tests pass.

One difference between my local experiment and travis is that is used the `travisci/ci-garnet:packer-1512502276-986baf0` docker image while travis seems to run `travisci/ci-garnet:packer-1512502259-986baf0`. The problem might come from the latter but the image doesn't seem to be publicly available.

**Comment by tiagocoutinho** [comment]
Hi all,
I have been running the tests on my machine and noticed a couple of things:
* My machine (a laptop) does not have a a permanent IP address so I am suffering from #246 
* After applying #247, all tests passed but... Each `test_mandatory_device_property` leaves a python process hanging loose.

When I run:
```
$ python setup.py test --addopts '-q -k "test_mandatory_device_property"'
============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /home/coutinho/workspace/tango/pytango, inifile: setup.cfg
plugins: xdist-1.25.0, forked-0.2
collected 657 items / 633 deselected                                           

tests/test_server.py ........................

================== 24 passed, 633 deselected in 12.17 seconds ==================

$ ps -ef | grep setup.py | grep -v grep
coutinho 30583  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30603  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30630  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30656  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30682  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30709  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30736  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30762  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30790  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30810  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30836  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30863  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30908  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30958  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 30985  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31011  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31037  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31058  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31084  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31110  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31137  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31163  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31189  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
coutinho 31216  2752  0 12:09 pts/0    00:00:00 python setup.py test --addopts -q -k "test_mandatory_device_property"
```
Is anyone else seeing this? Is it expected?

I am using PyTango 9.2.6, Tango C++ **9.3.2**, python 2.7.15 |Anaconda, Inc.| (default, Nov 13 2018, 23:04:45)

Notice I am using the newest Tango C++ **9.3.2**!!

**Comment by andygotz** [comment]
This is very good news that you are already using C++ 9.3.2!

**Comment by ajoubertza** [comment]
After some digging, it turns out that Travis CI build infrastructure has undergone [some significant changes](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) recently, and that is probably what has caused our tests to stop working.  Our builds have moved from container-based to VM-based.  Not sure why that breaks the events, but it seems to.

From the blog linked to above:

> Over the next few weeks, we encourage everyone to remove any `sudo: false` configurations from your `.travis.yml`. Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.
> 
> The timeline for this migration will be as follows:
> 
> 19 November, 2018 - Today we publish this post and are ready to answer all your questions!
> 28 November, 2018 - We will send a service email to remind folks still using sudo: false on recent builds to remind you to migrate.
> 03 December, 2018 - We will start randomly sampling projects on both travis-ci.org and travis-ci.com to move them permanently to using the virtual-machine-based infrastructure for all builds. The projects will be migrated incrementally over a few days
> 07 December, 2018 - All projects that use a Linux build environment will be fully migrated to using the same Linux infrastructure, which runs builds in virtual-machines.

Our last builds that worked ran on EC2, and used container image `travisci/ci-garnet:packer-1512502276-986baf0`  (which you can actually download and run yourself).

The current failing builds are running on GCE, and using VM image `travisci/ci-garnet:packer-1512502276-986baf0`.  I've also tried with their Ubuntu 16.04 VM image `travis-ci-sardonyx-xenial-1541445923-e193d27`, in PR #249.

I haven't found any web articles explaining how to download and running these new VMs locally.  Just how to use the old containers.

**Comment by tiagocoutinho** [comment]
@ajoubertza,

Nice research!

On my side, it seems that switching from hostname to host ip fixes the polling tests ([see here](https://travis-ci.org/tango-controls/pytango/jobs/469162170)). I don't understand why but also I didn't investigate further.

The event tests still fail but with a different error: before they failed to subscribe to the event. Now it seems they receive the first event (coming from an internal tango read attribute, so not through the ZMQ channel) but the first real event is not received.
My suspicion is that this the problem is at the ZMQ layer. Need to dig deeper :-)

**Comment by ajoubertza** [comment]
@tiagocoutinho Related to the events and hostnames vs IPs, another difference I see in the logs of old vs. new, is that previously there was just one IP, but now there are two.  Could that be part of the problem?  Maybe we're picking the wrong IP.

Logs from old container (working)
```
Local IP address and netmask pairs:
	172.17.0.2/255.255.0.0
```

Logs from new VM (failing)
```
Local IP address and netmask pairs:
	10.240.0.28/255.255.255.255
	172.17.0.1/255.255.0.0
```

**Review by ajoubertza — APPROVED** [review]
I'm happy with these changes.  The issues with the unit tests on Travis CI will be further investigated in PR #249.

**Pull request merged**
