### PR TITLE
WIP: fix the documentation build on python2.7 #244

### PR DESCRIPTION
**Pull request by aureocarneiro**
[python 2.7] ImportError: No module named mock #244

### CODE REVIEW

**Comment by ajoubertza** [comment]
@aureocarneiro Did you see [this comment](https://github.com/tango-controls/pytango/issues/244#issuecomment-444484671) in the original issue?  The code linked to there says: https://github.com/tango-controls/pytango/blob/ef4b465b71106beaec38c90db2dadee1fa3701dd/doc/mock_tango_extension.py#L22-L23

Are you planning to work around that patching problem in this PR?  Just fixing the import failure might not actually result in correct docs.

**Comment by jkotan** [comment]
Does it mean pytango drops support for python 2.7?

**Comment by ajoubertza** [comment]
> Does it mean pytango drops support for python 2.7?

No.  It just means that you should not try to build the docs when using Python 2.7.

In  `setup.py` there are already some checks that (I think) prevent docs being built:
https://github.com/tango-controls/pytango/blob/c32eb6ac374a9c27ecaa5780392194b491a6f9f5/setup.py#L229-L240

Try adding in a check in there:
```python
if sys.version_info < (3, 5):
    print("Documentation will not be generated:"
         " mocking the _tango extension requires python >= 3.5.")
    return False
```

If you don't have sphinx installed, then it won't try to build either, which is probably why most users don't notice this problem.

**Comment by ajoubertza** [comment]
Closing this old PR.  We don't need to build the docs on Python 2.

**Pull request closed without merging**
