### PR TITLE
Fix/linker options

### PR DESCRIPTION
**Pull request by ghost**
The setup.py adds an intended linker option which can cause problems later when trying to package the library. Please see commit messages for further details

### CODE REVIEW

**Comment by vxgmichel** [comment]
Thanks for your contribution! 

I'm curious though, what kind of problem did you encounter while building RPMs? At MAX-IV, we're using fpm and rpkg and they both work for packaging pytango.

@tiagocoutinho What was the purpose of those flags originally?

**Comment by tiagocoutinho** [comment]
These flags were a futile attempt to reduce the library size.
As far as I remember it was part of an effort to put pytango into embedded platforms were size matters.
This effort as never reached the light of day so I am ok with removing these flags. 
Probably this causes problems with nix packages.
If, in the future, we need stripping, we can add an optional flag to setup.py.

**Comment by vxgmichel** [comment]
OK thanks!

**Comment by ghost** [comment]
The RPMs are created using bitbake/yocto (a crosscompiling framework to create e.g. firmware for ARM). The RPMs are actually just an intermediary step used by bitbake before creating a flashable image. It might very well be that bitbake is using RPM slightly differently than e.g. rpkg.

[Sorry for responding so late, I seem to have missed your message back then.]

**Pull request merged**
