### PR TITLE
Fix compilation warnings and conda build

### LINKED ISSUE #286: Cleanup compilation warnings
A lot of compilation warnings occur when compiling pytango on linux.

99% of these warnings are coming from boost-python or 0MQ C++.

It would be nice to clean these until pytango replaces boost and 0MQ C++ fixes the warnings

### PR DESCRIPTION
**Pull request by tiagocoutinho**
Closes #286 

Also fixes issues with compiling pytango inside a conda environment

### CODE REVIEW

**Review by ajoubertza — CHANGES_REQUESTED** [review]
Nice to reduce warnings - I assume it wasn't feasible to fix the warnings (or they come from packages outside PyTango).

They Python 2.7 tests failed - looks like the latest pytest release no longer supports Python 2.  Please limit the version used on Python 2.  I'm guessing < 5.0.0.  https://github.com/pytest-dev/pytest/commit/4d49ba65297102110ae8aeecdb3b82b23a231fba

**Comment by tiagocoutinho** [comment]
Hi @ajoubertza ,
The warnings are external. They come from 0MQ and boost. The warning complaining that pytango uses deprecated `auto_ptr` is because boost requires it.

I can fix the pytest dependency but shouldn't pip figure out what is the latest pytest compatible with the python installation? Is this a pip limitation?

**Comment by tiagocoutinho** [comment]
Ok, it should be better now

**Comment by ajoubertza** [comment]
> I'll can fix the pytest dependency but shouldn't pip figure out what is the latest pytest compatible with the python installation? Is this a pip limitation?

Not pip limitation.  I think the [setup.py](https://github.com/pytest-dev/pytest/blob/183750fa86cecbfb2f5fbc5e3062d95299e84100/setup.py#L20) for pytest is missing a line like:  `python_requires='>=3.5'` so pip assumes it supports all versions.

**Review by ajoubertza — APPROVED** [review]

**Comment by ajoubertza** [comment]
More on the pip issue:
I get different results in different Python 2 environments.  In some it fails, in some it works.   I also see pytest has the requirement in [setup.cfg](https://github.com/pytest-dev/pytest/blob/157515f3c5b132eb1c126003c6d31a9bf36b1059/setup.cfg#L43).  Either way, our fix should work generally.

**Pull request merged**
