### PR TITLE
DeviceAttribute.is_empty was not working correctly with latest cpp tango version

### LINKED ISSUE #271: AttributeError: 'DeviceAttribute' object has no attribute 'value' for zero length arrays
With PyTango 9.3.0 some `deviceattribute` do not have `value` and `w_value` attributes.
this does not happened at least in v9.2.0.

You can reproduce the error:
```
import tango
dev_name = 'sys/tg_test/1'
dev = tango.DeviceProxy(dev_name)

for attr_name in ['short_spectrum', 'short_image', 'boolean_image', 'boolean_spectrum']:
    attr = dev.read_attribute(attr_name)
    print(attr.value)
```
With PyTango 9.2.0 you got `None`

### PR DESCRIPTION
**Pull request by jairomoldes**
fixes #271

### CODE REVIEW

**Review by tiagocoutinho — APPROVED** [review]

**Review by tiagocoutinho — CHANGES_REQUESTED** [review]
the PR should be against `develop`, not `stable`

**Review by ajoubertza — APPROVED** [review]
Thanks for the quick fix @jairomoldes (and remembering a cppTango change from a year an a half ago!)

**Comment by jairomoldes** [comment]
> the PR should be against `develop`, not `stable`

You are right. Sorry. My mistake.

**Comment by ajoubertza** [comment]
> the PR should be against `develop`, not `stable`

@tiagocoutinho This has been fixed, so I'm going to merge this.

**Comment by cpascual** [comment]
Just one comment:
IMHO, this PR is "patching" a backwards-incompatible change in Tango C++  regarding the zero-length arrays.
I completely agree with restoring the  the previous behaviour, but I think that this should (also) be done in TangoC++ to avoid the tango binding to differ in behaviour from the C++ library

**Comment by ajoubertza** [comment]
@cpascual Thanks for the comment - that sounds like an issue you need to raise in https://github.com/tango-controls/cppTango

**Comment by tiagocoutinho** [comment]
By principle, PyTango tries not to change the behaviour of the C++ library. Since a backward compatibility was introduced, I also think that the previous behaviour should be restored at the C++ level.

Regardless of the C++ team decision, this PR should be reverted because it masks some behaviour changes.

**Comment by ajoubertza** [comment]
>By principle, PyTango tries not to change the behaviour of the C++ library. Since a backward compatibility was introduced, I also think that the previous behaviour should be restored at the C++ level. 

Agree that PyTango behaviour should match the C++ library, but don't agree that this PR makes PyTango behave differently.  It makes PyTango's behaviour more accurate.  If the C++ library indicates that an attribute is empty, PyTango now correctly matches that behaviour.   Importantly, it makes PyTango's behaviour consistent with its previous behaviour.

> Regardless of the C++ team decision, this PR should be reverted because it masks some behaviour changes.

I don't think this PR should be reverted.  That would break PyTango functionality.  With this patch, PyTango works correctly with the C++ library 9.2.x and 9.3.x.  Why would we want to lose that?

**Pull request merged**
